import React from 'react';
import {createRoot} from 'react-dom/client';
import SiteShell from './components/site-shell';
import Home from './app/page';
import About from './app/about/page';
import Experience from './app/experience/page';
import Projects from './app/projects/page';
import Contact from './app/contact/page';
import {usePathname} from './paths';
import './app/globals.css';
const pages:Record<string,React.ComponentType>={'/':Home,'/about':About,'/experience':Experience,'/projects':Projects,'/contact':Contact};
const path=usePathname();const Page=pages[path]||Home;
document.title=(path==='/'?'Jessie Lu — Personal Portfolio':path.slice(1)[0].toUpperCase()+path.slice(2)+' | Jessie Lu');
createRoot(document.getElementById('root')!).render(<SiteShell><Page/></SiteShell>);
