import {siteUrl} from '../paths';
"use client";
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import ParticleText from './reactbits/ParticleText';
import SpotlightCard from './reactbits/SpotlightCard';
import Magnet from './reactbits/Magnet';
import DecryptedText from './reactbits/DecryptedText';
import {useQuietMotion} from './site-shell';
export function Heading({index,title,description}:{index:string,title:string,description?:string}){const quiet=useQuietMotion();return <div className="page-head"><div className="eyebrow">{index} / Jessie Lu</div><h1 aria-label={title}>{quiet?title:<DecryptedText text={title} animateOn="view" speed={35} maxIterations={7}/>}</h1>{description&&<p>{description}</p>}</div>}
export function HomeContent(){const quiet=useQuietMotion();return <><div className="shell hero reveal"><div className="hero-top eyebrow"><span>Information Systems / Carnegie Mellon</span><span>Pittsburgh, PA · Class of 2029</span></div><div className="hero-intro">Hi, I’m Jessie.</div><h1 className="hero-name">Jessie Lu</h1><div className="particle-wrap" aria-hidden="true">{quiet?<div className="static-name">JESSIE LU</div>:<ParticleText text="JESSIE LU" fontFamily="Arial, Helvetica, sans-serif" fontSize="clamp(78px, 16vw, 220px)" fontWeight={800} color="#d72c49" highlightColor="#ff6a80" particleSize={1.8} density={3} scatter={160} gatherDuration={1600} pointerRepel={55} repelRadius={100} idleDrift={0.12} glow={false}/>}</div><div className="hero-bottom"><h2>Curious about systems.<br/>Drawn to <em>possibility.</em></h2><div className="hero-actions"><Magnet disabled={quiet} padding={25} magnetStrength={7} innerClassName="magnet-inner"><a href={siteUrl("/projects")} className="pill primary">Explore my work <span>↗</span></a></Magnet><a href={siteUrl("/about")} className="pill">A little about me <span>↗</span></a></div></div><div className="hero-caption"><span>{quiet?'INFORMATION · COMPUTING · CURIOSITY':'MOVE YOUR CURSOR THROUGH THE LETTERS'}</span><span>SCROLL TO DISCOVER ↓</span><span>ALWAYS EXPLORING.</span></div></div><div className="marquee" aria-label="Interests: Information systems, algorithms, machine learning, quantitative thinking"><div className="marquee-inner" aria-hidden="true">{Array.from({length:4},(_,i)=><div key={i}>INFORMATION SYSTEMS <span>✳</span> ALGORITHMS <span>✳</span> MACHINE LEARNING <span>✳</span> QUANTITATIVE THINKING <span>✳</span> </div>)}</div></div><section className="section shell"><div className="section-heading"><h2>A few things I’ve explored.</h2><a href={siteUrl("/projects")} className="text-link">All projects ↗</a></div><div className="teasers"><SpotlightCard className="teaser" spotlightColor="rgba(215, 44, 73, 0.13)"><div className="eyebrow">01 / Research</div><h3><a href={siteUrl("/projects#cva-net")}>Finding patterns. Improving detection. ↗</a></h3><p>Co-authoring CVA-Net, a deep learning approach to lesion detection in breast ultrasound videos.</p></SpotlightCard><SpotlightCard className="teaser" spotlightColor="rgba(215, 44, 73, 0.13)"><div className="eyebrow">02 / Experience</div><h3><a href={siteUrl("/experience")}>Thinking under uncertainty. ↗</a></h3><p>Probability, simulated markets, and a second-place team finish in Jane Street’s WiSE Estimathon.</p></SpotlightCard></div></section></>}
export function ProjectCard({kind}:{kind:'research'|'code'}){const research=kind==='research';return <SpotlightCard className="project-card" spotlightColor="rgba(215, 44, 73, 0.12)"><div id={research?'cva-net':'python'} className="project-art" aria-hidden="true">{research?<div className="research-art"><div className="signal"/><div className="signal"/><div className="signal"/><div className="signal"/></div>:<div className="code-art">def explore():<br/>&nbsp;return possibility</div>}</div><div className="project-copy"><div className="eyebrow">{research?'01 / Machine learning research':'02 / Computational exploration'}</div><h2>{research?'CVA-Net':'Algorithms, games & probability'}</h2><p>{research?'Co-authored a research paper proposing a model that combines local and global temporal features to detect lesions in breast ultrasound videos.':'Built functional Python programs from scratch, exploring graph algorithms, game strategy, and discrete probabilistic systems.'}</p><div className="honors">{(research?['Python','Deep learning','ResNet-50']:['Python','Graph algorithms','Simulation']).map(t=><span className="badge" key={t}>{t}</span>)}</div><details><summary>Explore the work</summary><ul>{(research?['Pioneer Research Programme · February–December 2025','Used a ResNet-50 backbone to fuse local and global temporal features, with the aim of improving detection accuracy and robustness.','Developed foundational algorithm design, data handling, and model evaluation skills through linear algebra and weekly Python self-study.']:['Engineering Summer Academy at Penn · July 2025','Implemented graph algorithms and simulated systems including the halving game and tic-tac-toe.','Broke complex problems into reusable functions, developing skills in recursion, data modeling, and object-oriented thinking.']).map(t=><li key={t}>{t}</li>)}</ul></details></div></SpotlightCard>}
export function ContactContent(){const [message,setMessage]=useState('');const quiet=useQuietMotion();async function copy(){try{await navigator.clipboard.writeText('zhaojiel@andrew.cmu.edu');setMessage('Email copied.')}catch{setMessage('You can select and copy the email address above.')}}return <div className="shell contact-page reveal"><div className="page-head"><div className="eyebrow">04 / Contact</div></div><div className="contact-layout"><div><h1 className="contact-title">Let’s<br/><em>connect.</em></h1><a className="email" href="mailto:zhaojiel@andrew.cmu.edu">zhaojiel@andrew.cmu.edu ↗</a><div className="contact-actions"><Magnet disabled={quiet} padding={25} magnetStrength={7} innerClassName="magnet-inner"><a className="pill primary" href="mailto:zhaojiel@andrew.cmu.edu">Say hello ↗</a></Magnet><Button variant="outline" className="pill" onClick={copy}>Copy email</Button></div><p className="copy-status" role="status">{message}</p></div><aside className="contact-aside"><p>Have a project, a research question, or an interesting idea to share? I’d love to hear from you.</p><div className="facts"><div className="fact"><dt>Based in</dt><dd>Pittsburgh, PA</dd></div><div className="fact"><dt>Studying</dt><dd>Information Systems<br/>Carnegie Mellon University</dd></div></div></aside></div></div>}
